config/routes.rb
Spree::Core::Engine.add_routes do
  post '/paypal', :to => "paypal#express", :as => :paypal_express
  get '/paypal/confirm', :to => "paypal#confirm", :as => :confirm_paypal
  get '/paypal/cancel', :to => "paypal#cancel", :as => :cancel_paypal
  get '/paypal/notify', :to => "paypal#notify", :as => :notify_paypal

  namespace :admin do
    # Using :only here so it doesn't redraw those routes
    resources :orders, :only => [] do
      resources :payments, :only => [] do
        member do
          get 'paypal_refund'
          post 'paypal_refund'
        end
      end
    end
  end
end

app/views/spree/admin/payments/_paypal_complete.html.erb
<%= form_tag paypal_refund_admin_order_payment_path(@order, @payment) do %>
  <div class="label-block left five columns alpha">
    <div>
      <fieldset data-hook="admin_variant_new_form">
        <legend><%= Spree.t('refund', :scope => :paypal) %></legend>
        <div class='field'>
          <%= label_tag 'refund_amount', Spree.t(:refund_amount, :scope => 'paypal') %>
          <small><em><%= Spree.t(:original_amount, :scope => 'paypal', :amount => @payment.display_amount) %></em></small><br>
          <% symbol = ::Money.new(1, Spree::Config[:currency]).symbol %>
          <% if Spree::Config[:currency_symbol_position] == "before" %>
            <%= symbol %><%= text_field_tag 'refund_amount', @payment.amount %>
          <% else %>
            <%= text_field_tag 'refund_amount', @payment.amount %><%= symbol %>
          <% end %>
        </div>
        <%= button Spree.t(:refund, scope: 'paypal'), 'money' %>
      </fieldset>
    </div>
  </div>
<% end %>

app/views/spree/admin/payments/paypal_refund.html.erb
<%= render :partial => 'spree/admin/shared/order_tabs', :locals => { :current => 'Payments' } %>

<% content_for :page_title do %>
    / <%= link_to Spree.t(:payments), admin_order_payments_path(@order) %>
    / <%= payment_method_name(@payment) %>
    / <%= Spree.t('refund', :scope => :paypal) %>
<% end %>

<%= form_tag paypal_refund_admin_order_payment_path(@order, @payment) do %>
  <div class="label-block left five columns alpha">
    <div>
      <fieldset data-hook="admin_variant_new_form">
        <legend><%= Spree.t('refund', :scope => :paypal) %></legend>
        <div class='form-group'>
          <%= label_tag 'refund_amount', Spree.t(:refund_amount, :scope => 'paypal') %>
          <small><em><%= Spree.t(:original_amount, :scope => 'paypal', :amount => @payment.display_amount) %></em></small><br>
        </div>

        <% currency = ::Money::Currency.new(Spree::Config[:currency]) %>
        <div class="form-group">
          <div class="input-group">
            <% if currency.symbol_first %>
                <span class="input-group-addon" id="basic-addon1"><%= currency.symbol %></span>
                <%= text_field_tag 'refund_amount', @payment.amount, class: 'form-control' %>
            <% else %>
                <%= text_field_tag 'refund_amount', @payment.amount, class: 'form-control' %>
                <span class="input-group-addon" id="basic-addon1"><%= currency.symbol %></span>
            <% end %>
          </div>
        </div>

        <div class="form-group">
          <%= button Spree.t(:refund, scope: 'paypal'), 'money', class: 'btn btn-primary' %>
        </div>
      </fieldset>
    </div>
  </div>
<% end %>